name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  
jobs:
  build-backend:
    runs-on: ubuntu-latest
    strategy:
      matrix:
       node: [20.x]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/checkout@v4
        with:
          node-version: ${{matrix.node}}
          cache: 'npm'
          cache-dependency-path: 'app/backend/package-lock.json'

      - name: Install dependencies
        run: npm install
        working-directory: ./app/backend

  build-frontend:
    runs-on: ubuntu-latest
    strategy:
      matrix:
       node: [20.x]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/checkout@v4
        with:
          node-version: ${{matrix.node}}
          cache: 'npm'
          cache-dependency-path: 'app/frontend/package-lock.json'

      - name: Install dependencies
        run: npm install
        working-directory: ./app/frontend
    

     